image: docker:latest

services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: "ansible"
  REPOSITORY: "${CI_PROJECT_NAMESPACE}/${IMAGE_NAME}"

.build_template: &build_definition
  stage: build
  before_script:
    - echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_USER --password-stdin
  script:
    - if [ ! "${DEBUG}" = 'true' ]; then
        VARIANT="${ANSIBLE_VERSION}-${OS}-${OS_VARIANT}";
        docker pull "${REPOSITORY}:${VARIANT}" || true;
      else
        VARIANT="debug-${OS}-${OS_VARIANT}";
      fi
    - docker build
        --cache-from "${REPOSITORY}:${VARIANT}"
        -t "${REPOSITORY}:${VARIANT}"
        --build-arg BASE_IMAGE="${BASE_IMAGE}"
        "${OS}/"
    - if [ "${ANSIBLE_VERSION_OS_DEFAULT}" = 'true' ]; then
        docker tag "${REPOSITORY}:${VARIANT}" "${REPOSITORY}:"${ANSIBLE_VERSION}-${OS};
      fi
    - if [ "${OS_DEFAULT}" = 'true' ]; then
        docker tag "${REPOSITORY}:${VARIANT}" "${REPOSITORY}:${OS}";
      fi
    - if [ "${LATEST}" = 'true' ]; then
        docker tag "${REPOSITORY}:${VARIANT}" "${REPOSITORY}:latest";
      fi
    - docker images
    - docker run -t --rm ${REPOSITORY}:${VARIANT} /bin/sh -c "ansible --version"
    - if [ "${CI_COMMIT_REF_NAME}" = 'master' ] && [ ! "${DEBUG}" = 'true' ]; then
        docker push "${REPOSITORY}";
      fi
  after_script:
    - docker logout

.ubuntu_1804_template:
  variables:
    OS: "ubuntu"
    OS_VARIANT: "18.04"
    BASE_IMAGE: "ubuntu:bionic-20190204"
.alpine_38_template:
  variables:
    OS: "alpine"
    OS_VARIANT: "3.8"
    BASE_IMAGE: "alpine:3.8"

debug-ubuntu:
  extends: .ubuntu_1804_template
  variables:
    DEBUG: "true"
  <<: *build_definition
debug-alpine:
  extends: .alpine_38_template
  variables:
    DEBUG: "true"
  <<: *build_definition

2.7.8-ubuntu:
  extends: .ubuntu_1804_template
  variables:
    ANSIBLE_VERSION: "2.7.8"
    ANSIBLE_VERSION_OS_DEFAULT: "true"
    OS_DEFAULT: "true"
    LATEST: "true"
  <<: *build_definition
  when: manual
2.5.5-alpine:
  extends: .alpine_38_template
  variables:
    ANSIBLE_VERSION: "2.5.5"
    ANSIBLE_VERSION_OS_DEFAULT: "true"
    OS_DEFAULT: "true"
  <<: *build_definition
  when: manual