image: docker:latest

services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: "ansible"
  REPOSITORY: "${CI_PROJECT_NAMESPACE}/${IMAGE_NAME}"

.build_template: &build_definition
  stage: build
  before_script:
    - echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_USER --password-stdin
  script:
    - VARIANT="${TOOL_VARIANT}-${OS}-${OS_VARIANT}"
    - BASE_IMAGE="${OS}:${OS_VARIANT}"
    - docker pull "${REPOSITORY}:${VARIANT}" || true
    - docker build
        --cache-from "${REPOSITORY}:${VARIANT}"
        -t "${REPOSITORY}:${VARIANT}"
        --build-arg BASE_IMAGE="${BASE_IMAGE}"
        "${OS}/"
    - if [ "${DEFAULT}" = true ]; then
        docker tag "${REPOSITORY}:${VARIANT}" "${REPOSITORY}:${CI_JOB_NAME}";
        docker tag "${REPOSITORY}:${VARIANT}" "${REPOSITORY}:${OS}";
      fi
    - docker images
    - docker run -t --rm ${REPOSITORY}:${VARIANT} /bin/sh -c "ansible --version"
    - docker push "${REPOSITORY}"
  after_script:
    - docker logout
  when: manual

2.7.8-ubuntu:
  variables:
    TOOL_VARIANT: "2.7.8"
    OS: "ubuntu"
    OS_VARIANT: "18.04"
    DEFAULT: "true"
  <<: *build_definition

2.5.5-alpine:
  variables:
    TOOL_VARIANT: "2.5.5"
    OS: "alpine"
    OS_VARIANT: "3.8"
    DEFAULT: "true"
  <<: *build_definition
